name = "firebase-cloudflare-function"
type = "javascript"
node_compat = true

[vars]
OPENAI_API_KEY=process.env.OPENAI_API_KEY,
FIREBASE_ADMIN_CREDENTIALS=process.env.FIREBASE_ADMIN_CREDENTIALS,

[[workers.dev]]
account_id = "81f9092cf8df87e41d0c4d5ac9cc7244"
route = "https://ethanmckanna.workers.dev/*"
zone_id = "c14b0d5eac7306dcb9030fccebe44a18"

[build]
command = "npm run build"
upload = { format = "service-workers" }

[build.upload]
dir = "build"
main = "index.js"

[compatibility_flags]
nodejs_compat = true
