name = "firebase-cloudflare-function"
compatibility_date = "2023-01-01"
pages_build_output_dir = "./build"
nodejs_compat = true
node_compat = true

[vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
FIREBASE_ADMIN_CREDENTIALS = "${FIREBASE_ADMIN_CREDENTIALS}"

[build]
command = "npm run build"

# Add separate preview environment config if needed
[env.preview.vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
FIREBASE_ADMIN_CREDENTIALS = "${FIREBASE_ADMIN_CREDENTIALS}"
