name = "firebase-cloudflare-function"
compatibility_date = "2023-01-01"
pages_build_output_dir = "./build"
compatibility_flags = ["nodejs_compat"]

[vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
FIREBASE_ADMIN_CREDENTIALS = "${FIREBASE_ADMIN_CREDENTIALS}"

[env.preview.vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
FIREBASE_ADMIN_CREDENTIALS = "${FIREBASE_ADMIN_CREDENTIALS}"
