name = "firebase-cloudflare-function"
compatibility_date = "2023-01-01"
compatibility_flags = ["nodejs_compat"]

main = "./dist/moderate-comment.js"

[vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
FIREBASE_ADMIN_CREDENTIALS = "${FIREBASE_ADMIN_CREDENTIALS}"

[env.preview.vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
FIREBASE_ADMIN_CREDENTIALS = "${FIREBASE_ADMIN_CREDENTIALS}"
