name = "briefsnap-frontend"
compatibility_date = "2023-01-01"

[build]
command = "cd functions && npm install"

[functions]
directory = "functions"

[[functions.import]]
name = "moderate-comment"
module = "./functions/moderate-comment.js"

[vars]
OPENAI_API_KEY = "your-api-key-here"  # Replace with your actual API key
FIREBASE_ADMIN_CREDENTIALS = "your-firebase-admin-credentials-json-here"

# For local development:
[env.development.vars]
OPENAI_API_KEY = "your-api-key-here"

[env.production]
routes = [
  { pattern = "/api/moderate-comment", function = "moderate-comment" }
]
